# Generated by Django 2.2 on 2020-08-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorstop_api', '0005_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
