# Generated by Django 2.2 on 2020-08-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorstop_api', '0010_auto_20200828_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
