# Generated by Django 2.2 on 2020-08-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorstop_api', '0013_auto_20200828_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
