# Generated by Django 2.2 on 2020-08-31 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorstop_api', '0017_userprofile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('house_no_building_no', models.CharField(max_length=250)),
                ('road_name_area_colony', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('alternate_phone', models.CharField(max_length=10)),
                ('is_home', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
