# Generated by Django 2.2 on 2020-09-06 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorstop_api', '0018_addressobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='foods')),
                ('category', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], max_length=10)),
                ('cuisine', models.ManyToManyField(to='doorstop_api.Cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResturantFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorstop_api.Food')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorstop_api.Resturant')),
            ],
        ),
        migrations.AddField(
            model_name='resturant',
            name='foods',
            field=models.ManyToManyField(through='doorstop_api.ResturantFood', to='doorstop_api.Food'),
        ),
    ]
